#!/bin/bash

case "${1}" in
  configure)
    echo "Enabling & starting sagebk-registration service"
    systemctl enable sagebk-registration.service
    systemctl start sagebk-registration.service || true
    ;;
esac
